apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
      - name: week-22
        image: ghcr.io/vaishnaviv1105/week22:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
  selector:
    matchLabels:
      app: cicd