name: CI/CD Pipeline

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: DOcker login
        run: docker login --username ${{secrets.DOCKERHUB_USERNAME }} --password ${{secrets.DOCKERHUB_TOKEN }} ghcr.io

      - name: Docker build
        run: docker build . -t ghcr.io/vaishnaviv1105/week22:latest

      - name: Docker Run
        run: docker run -d --name week-22 -p 8080:80 ghcr.io/vaishnaviv1105/week22:latest

      - name: Docker Push
        run: docker push ghcr.io/vaishnaviv1105/week22:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Decode KUBECONFIG
        run: ${{ secrets.KUBECONFIG }} | base64 -d > $C:\Users\acer\.kube

      - name: Deploy to Kubernetes
        run: echo "Pipeline implemented successfully!!"